#include "KiyannaCodec.h"
#include "config.h"
#include <Wire.h>

#define ES8311_ADDR CODEC_ADDR

static void reg_write(uint8_t reg, uint8_t val) {
    Wire.beginTransmission(ES8311_ADDR);
    Wire.write(reg);
    Wire.write(val);
    Wire.endTransmission();
}

static uint8_t reg_read(uint8_t reg) {
    Wire.beginTransmission(ES8311_ADDR);
    Wire.write(reg);
    Wire.endTransmission(false);
    Wire.requestFrom((uint8_t)ES8311_ADDR, (uint8_t)1);
    return Wire.available() ? Wire.read() : 0xFF;
}

// Clock coefficients table (from ESP-ADF es8311.c)
// {mclk, rate, pre_div, pre_multi, adc_div, dac_div, fs_mode, lrck_h, lrck_l, bclk_div, adc_osr, dac_osr}
struct coeff_div {
    uint32_t mclk; uint32_t rate;
    uint8_t pre_div, pre_multi, adc_div, dac_div, fs_mode, lrck_h, lrck_l, bclk_div, adc_osr, dac_osr;
};

static const coeff_div coeff_table[] = {
    // 16kHz entries
    {12288000, 16000, 0x03, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {8192000 , 16000, 0x02, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {6144000 , 16000, 0x03, 0x02, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {4096000 , 16000, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {3072000 , 16000, 0x03, 0x04, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    // 24kHz entries
    {12288000, 24000, 0x02, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {6144000 , 24000, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    {3072000 , 24000, 0x01, 0x02, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10},
    // sentinel
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};

static int find_coeff(uint32_t mclk, uint32_t rate) {
    for (int i = 0; coeff_table[i].mclk != 0; i++) {
        if (coeff_table[i].mclk == mclk && coeff_table[i].rate == rate) return i;
    }
    return -1;
}

void es8311_init(uint32_t sample_rate) {
    // MCLK is generated by the I2S driver on I2S_MCLK pin — do NOT use LEDC here
    // (LEDC clock is 4.0MHz vs exact 4.096MHz needed — causes I2S sync failure)
    (void)sample_rate;

    Wire.begin(CODEC_I2C_SDA, CODEC_I2C_SCL, 400000);

    uint8_t id1 = reg_read(0xFD);
    uint8_t id2 = reg_read(0xFE);
    Serial.printf("[CODEC] ES8311 ID: 0x%02X 0x%02X\n", id1, id2);

    // ── Reset ───────────────────────────────────────────────────────────────
    reg_write(0x00, 0x1F);  // reset all
    delay(10);

    // ── Pre-init (matching ESP-ADF es8311_codec_init) ───────────────────────
    reg_write(0x01, 0x30);
    reg_write(0x02, 0x00);
    reg_write(0x03, 0x10);
    reg_write(0x16, 0x24);  // ADC init gain
    reg_write(0x04, 0x10);
    reg_write(0x05, 0x00);
    reg_write(0x0B, 0x00);  // analog power up
    reg_write(0x0C, 0x00);
    reg_write(0x10, 0x1F);  // ADC enabled, MIC bias on
    reg_write(0x11, 0x7F);  // reference voltage
    reg_write(0x00, 0x80);  // slave mode (ESP32 drives BCLK/WS)

    // ── Clock source: MCLK pin, no invert ───────────────────────────────────
    reg_write(0x01, 0x3F);
    uint8_t r01 = reg_read(0x01) & 0x7F;  // bit7=0: use MCLK pin
    r01 &= ~0x40;                          // bit6=0: not inverted
    reg_write(0x01, r01);

    // ── Clock dividers for mclk/rate pair ───────────────────────────────────
    uint32_t mclk = sample_rate * 256;
    int c = find_coeff(mclk, sample_rate);
    if (c < 0) {
        Serial.printf("[CODEC] WARNING: no coeff for mclk=%u rate=%u, using defaults\n", mclk, sample_rate);
    } else {
        const coeff_div& d = coeff_table[c];

        uint8_t pre_multi_code = 0;
        if (d.pre_multi == 2) pre_multi_code = 1;
        else if (d.pre_multi == 4) pre_multi_code = 2;
        else if (d.pre_multi == 8) pre_multi_code = 3;

        reg_write(0x02, (uint8_t)(((d.pre_div - 1) << 5) | (pre_multi_code << 3)));
        reg_write(0x05, (uint8_t)(((d.adc_div - 1) << 4) | ((d.dac_div - 1) << 0)));
        reg_write(0x03, (uint8_t)((d.fs_mode << 6) | d.adc_osr));
        reg_write(0x04, d.dac_osr);
        reg_write(0x07, d.lrck_h);
        reg_write(0x08, d.lrck_l);
        reg_write(0x06, (uint8_t)(d.bclk_div < 19 ? (d.bclk_div - 1) : d.bclk_div));
        Serial.printf("[CODEC] Clock: pre_div=%d bclk_div=%d lrck=%02X%02X\n",
            d.pre_div, d.bclk_div, d.lrck_h, d.lrck_l);
    }

    // ── I2S format: 16-bit, I2S standard, slave ──────────────────────────────
    // ES8311 SDP regs bits[7:5]: 000=24-bit, 011=16-bit; bits[1:0]: 00=I2S
    // 0x60 = 0b01100000 → 16-bit I2S (0x00 was wrong — that selects 24-bit)
    reg_write(0x09, 0x60);  // DAC SDP: 16-bit I2S
    reg_write(0x0A, 0x60);  // ADC SDP: 16-bit I2S

    // ── ADC/DAC final enable ─────────────────────────────────────────────────
    reg_write(0x0D, 0x03);  // bit0=DAC clock on, bit1=ADC clock on — both required
    reg_write(0x13, 0x10);
    reg_write(0x1B, 0x0A);
    reg_write(0x1C, 0x6A);
    reg_write(0x44, 0x00);  // 0x08 would route DAC→ADC (test mode) masking real mic

    // ADC unmute + DAC gain
    reg_write(0x15, 0x40);  // ADC ramp rate, unmute
    reg_write(0x31, 0x00);  // DAC unmute
    reg_write(0x32, 0x00);
    reg_write(0x37, 0x08);  // DAC output routing — 0x48 had bit6 set which mutes DAC-L
    reg_write(0x45, 0x00);

    // REG14: bit6=1 unmutes ADC input (critical — default after reset = muted)
    // bits[2:0] = analog PGA gain (5 = 15dB, 7 = 21dB)
    reg_write(0x14, 0x40 | 0x07);  // unmuted + 21dB analog PGA

    // ADC digital gain: PGA booster + volume
    reg_write(0x16, 0x6F);  // PGA digital boost
    reg_write(0x17, 0xBF);  // ADC digital volume 0dB

    // PA is enabled by KiyannaAudio::beginSpeaker() after I2S is stable.
    // Backlight is owned by KiyannaDisplay::begin() via LEDC PWM.

    Serial.println("[CODEC] ES8311 ready");
}
