[env:kiyanna-esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
src_dir = src

; MUMA ESP32-S3 N16R8 — 16MB Flash
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 524288

; Upload via USB Serial (CDC)
upload_port = /dev/cu.usbmodem101
upload_speed = 921600

monitor_port = /dev/cu.usbmodem101
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_unflags = -std=gnu++11

build_flags =
  -std=gnu++2a
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3

lib_deps =
  adafruit/Adafruit NeoPixel @ ^1.12.0
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  adafruit/Adafruit GFX Library @ ^1.11.10
  bblanchon/ArduinoJson @ ^7.0.0
